version: "3.9"

services:
  server:
    build: ./server
    ports:
     - "5000:5000"
    volumes:
      - ./server:/server

  web:
    build: ./react_client
    ports:
      - "3000:3000"
    volumes:
      - ./react_client:/usr/src/app
    
    depends_on:
      - server