version: "3.9"

services:
  server:
    build: ./server
    ports:
     - "5000:5000"
    volumes:
      - ./server:/server

  web:
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/app
    
    depends_on:
      - server